name: spaced
description: Spaced
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  url_launcher: ^6.2.2

dev_dependencies:
  custom_lint: ^0.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
