name: spaced
description: Spaced
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
